# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AxKit-Plugin-NotFoundIfPathInfo
version:      1.01
version_from: lib/Apache/AxKit/Plugin/NotFoundIfPathInfo.pm
installdirs:  site
requires:
    AxKit:                         1.60

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
